:sparkles: Add simple shadow ban
Traewelling/traewelling pull request #1509
Opened 2023-03-29 20:22 UTC by MrKrisKrisu

2023-03-29 20:31 UTC, xanderio requested changes

2023-03-29 20:31 UTC, xanderio commented on resources/views/profile.blade.php
> +                        @if(!$user->shadow_banned)
Shadow banned users should only disappear from the dashboard, there profile shouldn't be affected by this.

2023-03-29 20:39 UTC, MrKrisKrisu commented
I'll add an interaction in admin panel in another pr.

2023-03-29 20:47 UTC, xanderio approved these changes

2023-03-30 07:41 UTC, jeyemwey commented
Do we also want to ban the people from the global dashboard and the enroute views? Maybe thats something for another PR later :)

2023-03-30 10:23 UTC, MrKrisKrisu commented
> Do we also want to ban the people from the global dashboard and the enroute views? Maybe thats something for another PR later :)

Sounds useful.

2023-03-30 11:14 UTC, jeyemwey approved these changes

2023-03-30 13:08 UTC, merged