💄 Add Dark Mode
Traewelling/traewelling pull request #1685
Opened 2023-06-19 16:12 UTC by thilobillerbeck

At GPN I started to get the idea of implementing a dark mode since this is a common feature these days in web apps and will improve the usability of the site for people who prefer darker color schemes. Thus I started implementing a dark color scheme in combination with a toggle mechanism to manually switch between them. By default, the system preference will be picked.

The color scheme mainly focusses on a good readability with good but low contrasts to be easy on the eyes, espeacially in darker environments where bright colors can produce a lot of eyestrain. Meanwhile I tried to maintain the essence of the traewelling design to ensure people have the same experience as in light mode.

This is nearly finished but I still have to clean up some quirks, the code and maybe improve the switching mechanism. Meanwhile I want your help to improve everything in the last steps. This PR can be seen as a place to test and bring up some feedback to ensure a good experience for as many people as possible. 

Some questions to maybe help you giving feedback:

- How do you like the color scheme? What would you see as an improvement?
- What do you think about the switching mechanism? Is it okay like that or should it go into a drop down menu like the language selection?
- How do you feel about eyestrain while reading through the site? Especially in more crowded contexts like the feed.

2023-06-20 11:05 UTC, HerrLevin commented
One thing about the switching mechanism: I really like what getbootstrap.com is doing in their dropdown. They also include the possibility of "auto" so that the system settings can be (automatically) used. I really love that feature and I think many people will prefer a webpage/app to automatically respect their system preference.
![image](https://github.com/Traewelling/traewelling/assets/1267894/025145b4-3694-49f1-ada1-2c6c84b7633d)

2023-06-20 17:01 UTC, MrKrisKrisu commented
First of all: Thank you for your work! I love to see, that Trwl is getting an dark mode because of you. <3 

> How do you like the color scheme? What would you see as an improvement?

In general, I am very satisfied with the DarkMode. I find the readability of the red (trwl red) text on the dark background a bit difficult, but I would put that aside at this point unless you have an idea. Currently I have no idea how to make the trwl red fit better there. I also found some small things that are not perfect to read, like some buttons.

![image](https://github.com/Traewelling/traewelling/assets/4103693/fe53eb23-8fd7-4878-a9ec-2af9b039908c)

Also I am not fully happy with the color difference between the top nav bar, the jumbotron (e.g. on the profile page or the help page) and the dark background. But that are also some things to optimize maybe later step by step?

![image](https://github.com/Traewelling/traewelling/assets/4103693/725aadd9-03cb-412f-a977-967268555669)

Some messages (e.g. the "Checked in" message) are also still a bit light.

![image](https://github.com/Traewelling/traewelling/assets/4103693/13da210d-5d35-4424-ad3f-1099c39a1612)


> What do you think about the switching mechanism? Is it okay like that or should it go into a drop down menu like the language selection?

I would prefer a dropdown like @HerrLevin suggested. Maybe this would fit into the users dropdown in the top navbar?

> How do you feel about eyestrain while reading through the site? Especially in more crowded contexts like the feed.

Readability is good! As mentioned before, the only thing that bothers me a bit is the red text on a dark background.




I also noticed that when reloading a page or clicking on it, the dark mode is active by default (css class "dark" is set by default in the HTML). But if you use the light mode the page flickers. Maybe it is possible to implement a server-side saving of the darkmode settings, so that this can be syncedd across devices for a user.

2023-06-20 18:47 UTC, thilobillerbeck commented
> One thing about the switching mechanism: I really like what getbootstrap.com is doing in their dropdown. They also include the possibility of "auto" so that the system settings can be (automatically) used. I really love that feature and I think many people will prefer a webpage/app to automatically respect their system preference. ![image](https://user-images.githubusercontent.com/1267894/247095386-025145b4-3694-49f1-ada1-2c6c84b7633d.png)

Sounds good, I will try to port that over. But I think it should stay next to the language selection, since both are related to how the user interface behaves, while the top bar in traewelling is more related to the user context.

2023-06-20 18:54 UTC, thilobillerbeck commented
> First of all: Thank you for your work! I love to see, that Trwl is getting an dark mode because of you. <3
> 
> > How do you like the color scheme? What would you see as an improvement?
> 
> In general, I am very satisfied with the DarkMode. I find the readability of the red (trwl red) text on the dark background a bit difficult, but I would put that aside at this point unless you have an idea. 

What do you mean by difficult to read? Is it too popping or do you find it hard to distinguish from the rest of the elements?

> I also found some small things that are not perfect to read, like some buttons.
> 
> ![image](https://user-images.githubusercontent.com/4103693/247193589-fe53eb23-8fd7-4878-a9ec-2af9b039908c.png)

Oh seems like I have overlooked that.

> Also I am not fully happy with the color difference between the top nav bar, the jumbotron (e.g. on the profile page or the help page) and the dark background. But that are also some things to optimize maybe later step by step?

The problem with the jumbotron is, that the background values are embedded in the HTML while I try to do everything via CSS classes. I checked and don't see any point why it could not be ported over to the SCSS files. Then it would be easier for me to override the styles and it gets a lot easier to maintain anyway.

> Some messages (e.g. the "Checked in" message) are also still a bit light.
> ![image](https://user-images.githubusercontent.com/4103693/247195711-13da210d-5d35-4424-ad3f-1099c39a1612.png)

Yeah, overlooked that too.

> I would prefer a dropdown like @HerrLevin suggested. Maybe this would fit into the users dropdown in the top navbar?

As said in the comment before, I don't see how this fits logic wise, since all controls regarding the UI are currently situated at the end of the page. Otherwise this gets a full ACK.

> I also noticed that when reloading a page or clicking on it, the dark mode is active by default (css class "dark" is set by default in the HTML). But if you use the light mode the page flickers. Maybe it is possible to implement a server-side saving of the darkmode settings, so that this can be syncedd across devices for a user.

Yeah, that is one of the quirks im currently trying to solve.

2023-06-20 19:47 UTC, vainamov commented
![grafik](https://github.com/Traewelling/traewelling/assets/11841072/9a9b7c9c-73bc-4dd4-a541-938ffcbe9430)
I can not name what exactly bothers me about this, but either the color inside or the border color of the station indicator does not match

2023-06-20 20:35 UTC, thilobillerbeck commented
> ![grafik](https://github.com/Traewelling/traewelling/assets/11841072/9a9b7c9c-73bc-4dd4-a541-938ffcbe9430)
> I can not name what exactly bothers me about this, but either the color inside or the border color of the station indicator does not match 


Yeah, that bothers me as well. If you have any idea how to make that look better just let me know. I maybe fiddle around a but with some combinations.

2023-06-20 21:03 UTC, thilobillerbeck commented
Since this drives me crazy I'll start with the latter problem. The thing with the bulletpoints is, that the red, like it is already noticed,  can look quite agressive in dark scenarios. While the upper variant looks a bit out of place, coloring the whole point red is quite distracting from the rest of the card and draws to much attention for a decorative element imo.
![image](https://github.com/Traewelling/traewelling/assets/7442383/d3e79872-6c42-45a8-bd94-18ca3ce9b551)
The text besides looks like it is some kind of thing besides while it should draw the attention of the reader the most, since it is one of the most important parts of information on this card.

Coloring them in the base color makes them much more muted and the station names can get more attention by the reader. 
![image](https://github.com/Traewelling/traewelling/assets/7442383/df5a93a6-11d0-470c-ba96-e2ded8cba9dc)

I will continue to experiment with that. This just kind of describes my problem.

2023-06-20 21:11 UTC, thilobillerbeck commented
And to clarify that, the red of the shapes and the progress bar are the same as well as it is with the gray in the connecting line and the circles. The red used for the shaps is darkened already in comparison to the text, since it would appear much more bright otherwise since it covers a lot more space than text and to our eyes appears as a brighter color. That the gray in the circles appears not the same to our eyes as the one in the connecting line is an optical illusion as well.

@vainamov guess that bothers you less?
![image](https://github.com/Traewelling/traewelling/assets/7442383/efcbe2eb-eceb-46f9-94d0-1360fe80c983)

2023-06-20 21:38 UTC, vainamov commented
@thilobillerbeck Maybe of some part of me doesn't like the proportions of the element in general and it's just now that I realize that 😅

However, could you try `#3a3f4e` for the line and circle background? That's the color you use for the seperators in this screen: https://media.discordapp.net/attachments/1117889706097639524/1120133562344161290/localhost_8000_leaderboard.png?width=1872&height=1365

2023-06-23 19:39 UTC, thilobillerbeck commented
![image](https://github.com/Traewelling/traewelling/assets/7442383/180cd099-836f-4a3a-8df6-f0c258eb0a12)

@vainamov this is how it looks with your suggestion

2023-06-23 19:44 UTC, thilobillerbeck commented
@MrKrisKrisu, @HerrLevin I applied your suggestions as well, would appreciate a re-review. :)

2023-06-28 17:54 UTC, MrKrisKrisu requested changes

2023-06-28 17:54 UTC, MrKrisKrisu commented on resources/lang/en.json
> +    "settings.colorscheme.auto": "Sytem preference",
```suggestion
    "settings.colorscheme.auto": "System preference",
```

2023-06-28 17:55 UTC, MrKrisKrisu commented
> @MrKrisKrisu, @HerrLevin I applied your suggestions as well, would appreciate a re-review. :)

I like the new dropdown. :)
I'm not entirely happy with the position and size - especially in mobile view, but I don't have a good suggestion for this, so... lgtm. <3

2023-06-28 19:45 UTC, thilobillerbeck commented
> > @MrKrisKrisu, @HerrLevin I applied your suggestions as well, would appreciate a re-review. :)
> 
> I like the new dropdown. :)
> I'm not entirely happy with the position and size - especially in mobile view, but I don't have a good suggestion for this, so... lgtm. <3

I have something in mind but it is quite hard to implement in Bootstrap since it itself afaik does not ship with media query predicates like Tailwind. My idea would be to switch from row to a column layout on mobile devices and give each dropdown some space.

2023-07-05 19:45 UTC, MrKrisKrisu approved these changes

2023-07-05 19:47 UTC, merged