✨ apply event of original trip when joining
Traewelling/traewelling pull request #1745
Opened 2023-07-16 20:03 UTC by thilobillerbeck

This PR improves the join functionality by applying the event of the original trip when joining.

2023-07-24 15:40 UTC, MrKrisKrisu requested changes

2023-07-24 15:40 UTC, MrKrisKrisu commented on resources/js/appControls.js
> +            $(this).prop("checked", $(this).val() == source.trwlEventId);
Can this be applied here?
`Expected '===' and instead saw '=='.`

2023-07-26 16:49 UTC, MrKrisKrisu approved these changes
<3

2023-07-26 16:50 UTC, MrKrisKrisu commented
> **warning**
> This branch has conflicts that must be resolved

2023-07-26 17:56 UTC, thilobillerbeck commented
The conflicts seem to be resolved, just tested it locally

2023-07-26 17:56 UTC, merged