✨ Add stopovers to manual trips
Traewelling/traewelling pull request #2179
Opened 2023-12-01 22:11 UTC by HerrLevin

2024-01-19 19:03 UTC, MrKrisKrisu commented on app/Http/Controllers/Backend/Transport/ManualTripCreator.php
> +    public function generateUniqueTripId(): string {
why? this function doesn't belong to any object things.

2024-01-30 21:37 UTC, HerrLevin commented
@MrKrisKrisu Please checkout this branch and test its functionality locally. You don't have to review it if you don't want to. Just want to assure that I didn't ruin the functionality. :D

2024-02-01 19:11 UTC, MrKrisKrisu commented on app/Http/Controllers/API/v1/TripController.php
> +                'stopovers'                 => ['nullable', 'array'],
(self note) is this required?

2024-02-01 19:11 UTC, MrKrisKrisu commented on app/Http/Controllers/API/v1/TripController.php
> +                    Station::where('ibnr', $stopover['stationId'])->firstOrFail(),
(self note) catch wrong Ids before

2024-02-01 19:11 UTC, MrKrisKrisu commented on app/Http/Controllers/API/v1/TripController.php
> +                    Station::where('ibnr', $stopover['stationId'])->firstOrFail(),
(self note) use ID - not IBNR! We are going away from the IBNR as a primary key to support more identifier.

2024-02-01 19:11 UTC, MrKrisKrisu commented on app/Http/Controllers/Backend/Transport/ManualTripCreator.php
> +    ): ManualTripCreator {
(self note) if departure > arrival = throw exception

2024-02-01 19:28 UTC, MrKrisKrisu requested changes

2024-02-01 19:28 UTC, MrKrisKrisu commented on resources/vue/components/TripCreation/TripCreationForm.vue
> +            this.form.journeyNumber = isNumber(this.trainNumberInput) ? this.trainNumberInput : null;
journeyNumber is now ignored?

2024-02-01 19:28 UTC, MrKrisKrisu commented on resources/vue/components/TripCreation/TripCreationForm.vue
> +            this.form.journeyNumber = isNumber(this.trainNumberInput) ? this.trainNumberInput : null;
![image](https://github.com/Traewelling/traewelling/assets/4103693/ddd53bd6-93f4-4d7e-b7bd-a908670b1d1f)
![image](https://github.com/Traewelling/traewelling/assets/4103693/244a2c43-c73f-46ee-b34e-42dded50d00e)

2024-02-01 19:32 UTC, MrKrisKrisu commented on app/Http/Controllers/API/v1/TripController.php
> +                    Station::where('ibnr', $stopover['stationId'])->firstOrFail(),
I'll change this in another PR, because IBNR is used multiple times in existing code here.

2024-02-01 19:40 UTC, MrKrisKrisu requested changes

2024-02-01 19:40 UTC, MrKrisKrisu commented on resources/vue/components/TripCreation/TripCreationForm.vue
> +                    v-on:update:timeFieldA="setStopoverArrival($event, key)"
Is the input for departure and arrival switched? @HerrLevin

2024-02-01 19:41 UTC, MrKrisKrisu commented on resources/vue/components/TripCreation/TripCreationForm.vue
> +                    v-on:update:timeFieldA="setStopoverArrival($event, key)"
(left arrival and right departure?)

2024-02-01 19:54 UTC, MrKrisKrisu commented
my change requests can be fixed in another pr @HerrLevin

2024-02-01 19:54 UTC, merged