:card_file_box: migrate trips table to use ID instead of IBNR
Traewelling/traewelling pull request #2422
Opened 2024-03-11 18:45 UTC by MrKrisKrisu

see #2411

2024-03-11 19:00 UTC, MrKrisKrisu commented
"SQLite doesn't support dropping foreign keys (you would need to re-create the table)."

(╯°□°)╯︵ ┻━┻

2024-03-21 20:05 UTC, HerrLevin requested changes

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2023_11_21_000002_add_default_permissions.php
> +        // empty now - replaced by PermissionSeeder
Hm. Not a fan. Why is this needed?
Also:
- This file should be deleted
- Moving this logic from a migration to a seeder should be a separate PR (imho)

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2023_12_17_000003_add_event_history_permission.php
> +        // empty now - replaced by PermissionSeeder
Hm. Not a fan. Why is this needed?
Also:
- This file should be deleted
- Moving this logic from a migration to a seeder should be a separate PR (imho)

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2024_01_29_000000_add_station_permissions.php
> +        // empty now - replaced by PermissionSeeder
Hm. Not a fan. Why is this needed?
Also:
- This file should be deleted
- Moving this logic from a migration to a seeder should be a separate PR (imho)

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2024_01_30_000000_add_activity_permissions.php
> +        // empty now - replaced by PermissionSeeder
Hm. Not a fan. Why is this needed?
Also:
- This file should be deleted
- Moving this logic from a migration to a seeder should be a separate PR (imho)

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2024_02_01_000000_add_permissions_for_manual_trips_beta.php
> +        // empty now - replaced by PermissionSeeder
Hm. Not a fan. Why is this needed?
Also:
- This file should be deleted
- Moving this logic from a migration to a seeder should be a separate PR (imho)

2024-03-21 20:05 UTC, HerrLevin commented on database/seeders/DatabaseSeeder.php
> +        $this->call(PermissionSeeder::class);
Idk, I don't really like that.

2024-03-21 20:05 UTC, HerrLevin commented on app/Http/Controllers/API/v1/StationController.php
> -        Trip::where('origin', $oldStation->ibnr)->update(['origin' => $newStation->ibnr]);
Shouldn't you keep these for legacy Trips  without a origin/destination id?

2024-03-21 20:05 UTC, HerrLevin commented on app/Http/Controllers/HafasController.php
> -                                         'origin'         => $origin->ibnr,
Shouldn't you keep these for legacy Trips  without a origin/destination id?

2024-03-21 20:05 UTC, HerrLevin commented on app/Models/Trip.php
> -        'origin'         => 'integer',
Shouldn't you keep these for legacy Trips  without a origin/destination id?

2024-03-21 20:05 UTC, HerrLevin commented on app/Models/Trip.php
> -        return $this->belongsTo(Station::class, 'origin', 'ibnr');
Shouldn't you keep these for legacy Trips  without a origin/destination id?

2024-03-21 20:05 UTC, HerrLevin commented on app/Models/Trip.php
> -        return $this->belongsTo(Station::class, 'destination', 'ibnr');
Shouldn't you keep these for legacy Trips  without a origin/destination id?

2024-03-21 20:05 UTC, HerrLevin commented on database/migrations/2024_03_11_000000_add_origin_and_destination_id_to_trips.php
> +        DB::table('hafas_trips')->update([
Won't this be like... suuuuper slow? We currently have over 2 million trips. These 4 lines should equate to at least ~6 Million Queries.

2024-03-21 23:33 UTC, HerrLevin commented on database/migrations/2024_03_11_000000_add_origin_and_destination_id_to_trips.php
> +    public function up(): void {
This migration should be split into multiple migrations and maybe moved into transactions.

2024-03-22 10:54 UTC, MrKrisKrisu commented
@HerrLevin As discussed: I'll split up this PR in multiple small PR's and do separate migrations for create and drop the data for security reasons (data loss).

2024-03-22 10:56 UTC, HerrLevin commented
@MrKrisKrisu Not necessarily multiple PRs but multiple migrations. :)

2024-05-21 07:26 UTC, closed without merging