:card_file_box: migrate trips table to use ID instead of IBNR
Traewelling/traewelling pull request #2443
Opened 2024-03-22 11:22 UTC by MrKrisKrisu

2024-03-22 11:47 UTC, MrKrisKrisu commented
Tested with prod data ~ 21,3 minutes
![image](https://github.com/Traewelling/traewelling/assets/4103693/f17dfe0c-a4d1-426c-acc5-c25181f577b7)

2024-05-10 10:39 UTC, HerrLevin requested changes

2024-05-10 10:39 UTC, HerrLevin commented on app/Models/Trip.php
> +        return $this->belongsTo(Station::class, 'origin_id', 'id');
Geht das in jedem Fall? Das setzt ja voraus, dass jeder Trip schon aktualisiert wurde, dass uns die relations nicht kaputt gehen, oder sehe ich das falsch?

2024-05-10 10:39 UTC, HerrLevin commented on database/migrations/2024_03_22_000000_add_origin_and_destination_id_to_trips.php
> +            $table->foreign('destination_id')->references('id')->on('train_stations');
Bitte testen, aber das fände ich schlanker

```suggestion
            $table->foreignId('origin_id')->references('id')->on('train_stations')->nullable()->after('origin');
            $table->foreignId('destination_id')->references('id')->on('train_stations')->nullable()->after('destination');
```

2024-05-10 10:40 UTC, HerrLevin commented on app/Models/Trip.php
> +        return $this->belongsTo(Station::class, 'origin_id', 'id');
Hab weiter unten die Migration gesehen. Nvm. :D

2024-05-10 10:41 UTC, HerrLevin approved these changes
Okay, ne. Eigentlich passt alles für mich. der Kommentar wäre nice to have.

2024-05-21 07:11 UTC, merged