🐛 Fixed likes
Traewelling/traewelling pull request #344
Opened 2021-05-15 16:10 UTC by MrKrisKrisu

2021-05-16 13:08 UTC, HerrLevin requested changes
better practice would be to change the data-tag in the view to `data-trwl-statusid`

2021-05-16 20:41 UTC, MrKrisKrisu commented
> better practice would be to change the data-tag in the view to `data-trwl-statusid`

I don't understand?

2021-05-17 09:34 UTC, HerrLevin commented
> I don't understand?

I started using `data-trwl-XXX` in the HTML instead of `data-XXX` to better distinguish our data-attributes from those of other things (just like bootstrap/mdb does with `data-md-xxx`/`data-bs-xxx`). It would be better to change the name of the data-attributes in the HTML to the newer standard than changing the js back to the old one. 

For reference: `data-trwl-asdf` would translate to `data.trwlAsdf`in JS.

2021-05-19 06:49 UTC, HerrLevin approved these changes

2021-05-19 06:51 UTC, merged