🚑️ Critical Hotfix: Fixed Leaderboard data and performance
Traewelling/traewelling pull request #383
Opened 2021-05-28 14:39 UTC by MrKrisKrisu

The leaderboard now shows the correct data again (last 7 days, or selected month). Also, it is now 27x faster than before this change.

The API v1 endpoint needs to be adjusted.

2021-05-29 20:51 UTC, HerrLevin requested changes

2021-05-29 20:51 UTC, HerrLevin commented on resources/views/leaderboard/month.blade.php
> +                    <em class="fas fa-arrow-left"></em> {{$date->clone()->subMonth()->isoFormat(__('dateformat.month-and-year'))}}
please change <em> tags back to <i> tags with a `aria-hidden=true`-Tag.

2021-06-06 13:01 UTC, HerrLevin approved these changes

2021-06-06 13:01 UTC, HerrLevin commented on resources/views/leaderboard/month.blade.php
> +                        <i class="fas fa-arrow-right"></i>
they're still missing the `aria-hidden="true`

2021-06-06 13:01 UTC, merged

2021-06-06 13:03 UTC, MrKrisKrisu commented on resources/views/leaderboard/month.blade.php
> +                        <i class="fas fa-arrow-right"></i>
I don't want to change this here because the PR is about a different topic.