✨ Add user search to vue + api
Traewelling/traewelling pull request #564
Opened 2021-10-17 12:43 UTC by HerrLevin

2021-10-17 14:32 UTC, MrKrisKrisu commented
Please change the base branch from `main` to `develop`.

2021-10-18 11:14 UTC, MrKrisKrisu requested changes

2021-10-18 11:14 UTC, MrKrisKrisu commented on app/Http/Controllers/Backend/UserController.php
> +        $validator = Validator::make(['searchQuery' => $searchQuery], ['searchQuery' => 'required|alpha_num']);
```suggestion
        $validator = Validator::make(['searchQuery' => $searchQuery], ['searchQuery' => ['required', 'alpha_num']]);
```

2021-10-18 11:14 UTC, MrKrisKrisu commented on app/Http/Controllers/Backend/UserController.php
> +        )->simplePaginate(10);
I don't like Paginator as a return type. Can you change this to return either an Collection or just the query?

2021-10-18 14:14 UTC, HerrLevin commented on app/Http/Controllers/Backend/UserController.php
> +        )->simplePaginate(10);
And how do we paginate the entire response? 😅

2021-10-18 14:48 UTC, MrKrisKrisu commented on app/Http/Controllers/Backend/UserController.php
> +        )->simplePaginate(10);
One way is to just remove the `->simplePaginate(10);` here and return the raw non-executed query. You can use the simplePaginate in your API Frontend and if another code-block needs the result in this function in another way it can be easily used. But a paginate in the backend is too limited.

2021-10-24 12:42 UTC, MrKrisKrisu approved these changes

2021-10-24 12:44 UTC, merged