🚀 Docker image for easier deployment
Traewelling/traewelling pull request #585
Opened 2021-10-27 20:32 UTC by aledjones

- [x] Dockerfile: creates image with prebuilt webpack
- [x] Dockerfile: has maintainer labels
- [x] Dockerfile: use composer image
- [x] docker-entrypoint.sh: migrates current database on start
- [ ] docker-entrypoint.sh: locking mechanism for database migration
- [ ] docker-entrypoint.sh: error-handling
- [ ] docker-entrypoint.sh: locking state validation
- [x] GitHub Actions: Images are built on push to defined branches
- [x] GitHub Actions: Images are built and tagged with commit id
- [x] GitHub Actions: Images are pushed to GitHub Registry tagged with the gut reference that started the build (branch push or tag release)

2021-10-28 08:22 UTC, MrKrisKrisu requested changes

2021-10-28 08:22 UTC, MrKrisKrisu commented on Dockerfile
> +FROM php as PHPBuildContainer
Can you specify PHP 8.0?

2021-10-28 08:22 UTC, MrKrisKrisu commented on app/Providers/AppServiceProvider.php
> +        if (env('APP_ENV') === 'prod') {
```suggestion
        if (config('app.env') === 'prod') {
```

2021-10-28 08:22 UTC, MrKrisKrisu commented on docker-entrypoint.sh
> +    runuser -u www-data -- php artisan migrate
```suggestion
    runuser -u www-data -- php artisan migrate --force
```

Isn't this required?

2021-10-28 08:22 UTC, MrKrisKrisu commented on Dockerfile
> +RUN docker-php-ext-install gd exif
We have already talked about that. In the long run, we should use a composer image and set a version. I have written it on the todo. But it is non-blocking for me.

2021-10-28 08:22 UTC, MrKrisKrisu commented on Dockerfile
> +FROM php:apache
Can you specify PHP 8.0?

2021-10-28 08:22 UTC, MrKrisKrisu commented on .htaccess
> +RewriteRule ^ index.php [L]
What is the file needed for? It is located in the root directory.

In the public folder I would understand it.

2021-10-28 08:22 UTC, MrKrisKrisu commented on .github/workflows/docker.yml
> +      - dev-*
I would not build a container on our dev-* branches. Or do you think that makes sense?

2021-10-28 08:22 UTC, MrKrisKrisu commented on .dockerignore
> +.git
maybe also add vendor/ and node_modules? This would at least be useful for local building.

2021-10-28 19:49 UTC, aledjones commented on .dockerignore
> +.git
Will do

2021-10-28 19:50 UTC, aledjones commented on .github/workflows/docker.yml
> +      - dev-*
This was only a suggestion for easier local and on-premise testing like in cloud environments...
I'll remove those entries as they can be added back in the future

2021-10-28 19:52 UTC, aledjones commented on .github/workflows/docker.yml
> +      - dev-*
On second thought: this is the only way to test docker builds in my PR branch.
It'll stay and be removed as soon as we merge into develop.

2021-10-28 19:54 UTC, aledjones commented on .htaccess
> +RewriteRule ^ index.php [L]
This file just shows that I'm an idiot that didn't put together a laravel container for a very long time.
Will be removed in upcoming changes.

2021-10-28 19:55 UTC, aledjones commented on Dockerfile
> +FROM php as PHPBuildContainer
Will do.

2021-10-28 20:57 UTC, aledjones commented on Dockerfile
> +RUN docker-php-ext-install gd exif
Changes to `composer:2` in upcoming commit

2021-10-29 19:28 UTC, MrKrisKrisu requested changes

2021-10-29 19:28 UTC, MrKrisKrisu commented on app/Providers/AppServiceProvider.php
> +        if (config('app.env') === 'prod') {
```suggestion
        if (config('app.env') === 'production') {
```
Sorry, I missed that last time. xD

2021-10-29 19:50 UTC, MrKrisKrisu approved these changes

2021-10-29 19:52 UTC, merged