✨ Modify the checkin flow to give more insights about points and the ability to force checkin
Traewelling/traewelling pull request #621
Opened 2021-11-08 16:19 UTC by HerrLevin

![image](https://user-images.githubusercontent.com/1267894/140778583-e5b0a3e3-95bb-4ecb-8d71-a93031b9a849.png)

2021-11-21 15:29 UTC, MrKrisKrisu requested changes

2021-11-21 15:29 UTC, MrKrisKrisu commented on app/Http/Resources/PointsCalculationResource.php
> +                'distance' => $this['calculation']['distance'], //TODO: This isn't the distance! Should be renamed.
See ToDo

2021-11-24 14:41 UTC, HerrLevin commented on app/Http/Resources/PointsCalculationResource.php
> +                'distance' => $this['calculation']['distance'], //TODO: This isn't the distance! Should be renamed.
Refactor in a future PR and merge now?

2021-11-25 09:44 UTC, MrKrisKrisu approved these changes

2021-11-25 09:46 UTC, merged